stages:
  - compile
  - build

services:
  - docker:dind

variables:
  USER: "hfxdevopdemo"
  
# This stage compiles the webserver code and then artifacts the binary & html for 1 week
Build Web Server:
  image: docker.io/golang
  stage: compile
  environment: qa
  script:
    - find . -name "webserver.go" -exec go build {} \;
  artifacts:
    paths: 
    - webserver
    - devops.html
    expire_in: 1 week
  
# This stage builds the docker image and tags it as hfxdevopdemo/simpleweb:dev, it then pushes it to Docker Hub. 
# We're using protected project variables for the user/password.
Build Test Docker Image:
  stage: build
  environment: dev
  script:
    - docker login -u $USER -p $PASSWORD
    - docker build -t hfxdevopdemo/simpleweb:dev .
    - docker push hfxdevopdemo/simpleweb:dev
    
# This stage builds the docker image and tags it as hfxdevopdemo/simpleweb:latest, it then pushes it to Docker Hub. 
# We're using protected project variables for the user/password.
Build Docker Image:
  stage: build
  environment: prod
  script:
    - docker login -u $USER -p $PASSWORD
    - docker build -t hfxdevopdemo/simpleweb:latest .
    - docker push hfxdevopdemo/simpleweb:latest
  only:
    - master
