stages:
  - compile
  - build

services:
- docker:dind

Build Web Server:
  image: docker.io/golang
  stage: compile
  environment: qa
  script:
    - find . -name "webserver.go" -exec go build {} \;
  artifacts:
    paths: 
    - webserver
    - devops.html
    expire_in: 1 week
  
 
Build Docker Image:
  stage: build
  script:
    - docker login -u $USER -p $PASSWORD
    - docker build -t hfxdevopdemo/simpleweb:latest .
    - docker push hfxdevopdemo/simpleweb:latest
    
